package chatapplication;

import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author n00153466
 */
public class Client extends javax.swing.JFrame {

    static Socket socket;
    static DataInputStream dtinput;
    static DataOutputStream dtoutput;

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //auto generated text from JForm design interface.
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msgDispField = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        typedTextBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");

        msgDispField.setEditable(false);
        msgDispField.setColumns(20);
        msgDispField.setLineWrap(true);
        msgDispField.setRows(5);
        jScrollPane1.setViewportView(msgDispField);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Type your Message Here:");

        typedTextBox.setColumns(20);
        typedTextBox.setRows(5);
        typedTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                typedTextBoxKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(typedTextBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //auto generated event listener for the send button click event.
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sendMessage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void typedTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typedTextBoxKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sendMessage();
        }
    }//GEN-LAST:event_typedTextBoxKeyPressed

    private void sendMessage() {
        try {
            String msgOut = "";                                 //declares a sent message variable and sets the text field to be empty before typing
            msgOut = typedTextBox.getText().trim();             //gets the text typed in the text field
            dtoutput.writeUTF(msgOut);                          //uses dataOutputStream writeUTF method and passes the variable msgOut which contains the text typed in the text box.
            //        msgDispField.setText("me: "+typedTextBox.getText().trim());
            //        msgDispField.setText("Test 1" + "\nme: "+typedTextBox.getText().trim());
            //        msgDispField.setText(msgDispField.getText() + System.lineSeparator() + "me: "+typedTextBox.getText().trim());
            msgDispField.append(System.lineSeparator() + "Me: " + msgOut);   //displays the message that the client typed and adds me: infront of it.
            typedTextBox.setText("");                           //resets the text box to be empty after the message is sent.
        } catch (IOException e) {
            System.out.println("Error" + e.getMessage());        //catches any exceptions and displays them in the console.
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {    //method invoked when the application is launched
            public void run() {
                new Client().setVisible(true);              //makes the client window visible.       
            }
        });

        try {                                                            //receives text message from the server and displays it in the chat box
            socket = new Socket("127.0.0.1", 1201);                      //creates new socket using the server ip which in this case is local host and server port.
            dtinput = new DataInputStream(socket.getInputStream());     //gets input stream that is later used to display the message sent from the server to the client.
            dtoutput = new DataOutputStream(socket.getOutputStream());  //data output stream sends out the message.
            String msgIn = "";                                          //declares the message in variable that is used to display the message in the message window

            while (!msgIn.equals("Exit")) {                             //this loop runs till the message is Exit.
                msgIn = dtinput.readUTF();                              //reads the input stream UTF
                msgDispField.setText(msgDispField.getText().trim() + "\n Server: " + msgIn);    //displays the message sent from the server.
            }
        } catch (IOException e) {
            System.out.println(e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea msgDispField;
    private javax.swing.JTextArea typedTextBox;
    // End of variables declaration//GEN-END:variables
}
